<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_User LoginName password Login</name>
   <tag></tag>
   <elementGuidId>0233a31b-0320-4f7a-839e-89a6a593fb68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.card</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/form/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>908c02e4-a362-422f-8b68-128801b5c282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card</value>
      <webElementGuid>35af2dba-267e-4e24-bb04-8cc3cc8187e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User LoginName password Login</value>
      <webElementGuid>17d1c292-b7db-47ac-9002-d90a04d83ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;offset-lg-3 col-lg-6&quot;]/form[@class=&quot;container&quot;]/div[1]/div[@class=&quot;card&quot;]</value>
      <webElementGuid>291c864b-8339-4264-bf00-271571695842</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div/div</value>
      <webElementGuid>6a8f4490-0870-4a3c-b54c-0edaeb531054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='React JS CRUD Assesment'])[1]/following::div[4]</value>
      <webElementGuid>bb0b45fe-1e6c-456b-b8e7-28ccee700e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div</value>
      <webElementGuid>392a0aa6-a874-45c2-bbc4-4febcc4ac3e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'User LoginName password Login' or . = 'User LoginName password Login')]</value>
      <webElementGuid>6673e969-e2b0-4ee5-99da-ff01c2fbbefe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
