<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone_inputphone</name>
   <tag></tag>
   <elementGuidId>6ab2c787-3287-4a22-b03b-52194874432f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputphone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputphone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8dccde77-7f0c-4795-a486-119fe8fb9bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputphone</value>
      <webElementGuid>7b5b6598-73c0-4a73-9fc0-910baf622bba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4631bb31-9b26-4107-9855-f737f48e161d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e1bf3f16-8b85-476e-b28b-d8be750ba4eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputphone&quot;)</value>
      <webElementGuid>a22b52f6-62d8-43de-95ec-358c4b2455d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputphone']</value>
      <webElementGuid>ef47af16-3578-4184-be53-e039ba52fc61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/form/div/div[2]/div/div[3]/div/input</value>
      <webElementGuid>0ec71e13-8573-4a2b-8ecc-18d7ba235a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>a57ad443-d2f8-4fee-851c-93a40d0593f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputphone' and @type = 'number']</value>
      <webElementGuid>19b3d75e-f068-41fe-afa7-28fd19d0fe86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
