<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_inputpassword</name>
   <tag></tag>
   <elementGuidId>c9964430-7588-4529-b30e-42f44c511d8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputpassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputpassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f2be0247-be35-41e4-8718-04cfafebcd06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputpassword</value>
      <webElementGuid>d07f18ec-0ffa-4550-bf47-68830b0df503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b62cd391-0b9b-486a-b50c-71f9f770a536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b4ef3af7-c9ea-4e27-834c-6a0674e223bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>6fda5946-652b-4d69-afb7-405a3288a14a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputpassword&quot;)</value>
      <webElementGuid>4d3bb3ce-7d9a-42d1-ab65-08c16b8582e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputpassword']</value>
      <webElementGuid>9cd034eb-0145-4939-8b37-29b8dfca2efc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/form/div/div[2]/div/div[4]/div/input</value>
      <webElementGuid>1bd7d7db-8af0-4b2f-9a21-3ed98e6f0b9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>bba3c906-a4d8-4444-8c5c-ec5f918013c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputpassword' and @type = 'password']</value>
      <webElementGuid>cb3e22f6-27ea-4c25-872a-4b550fab1773</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
