<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_inputemail</name>
   <tag></tag>
   <elementGuidId>2bc03ebf-507f-4374-9bce-f4a86996decc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputemail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputemail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d58c8c9-47b2-41ad-8e0b-406d7290c860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputemail</value>
      <webElementGuid>130ad443-1630-4eb3-b74c-9cc1153cbd07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>08798162-b224-4271-b013-64d9369b6251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c06040c0-c4e0-48f0-b355-c50ed248bbf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fa405e73-d1ec-4669-ba59-bb61e82a9bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputemail&quot;)</value>
      <webElementGuid>d3f73fc2-bb25-45ab-a6d5-ab7cba3ed1b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputemail']</value>
      <webElementGuid>8ba507f2-189b-4a62-a97a-d0ac689f1046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/form/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>8cffc570-304e-403c-8a3f-5f0d8193d6fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>42d8c062-af2c-43c4-b7bc-e569c627fc1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputemail' and @type = 'email']</value>
      <webElementGuid>d115d09f-144e-4211-8ff9-f227c123cb45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
